# Generated by Django 2.1.5 on 2019-02-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='name1',
            field=models.CharField(max_length=1000),
        ),
    ]
